# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: Environment
    displayName: 'Choose an option'
    type: string
    default: 'Dev'
    values:
      - Dev
      - Test
      - Prod

variables:
- group: Simplifier
- name: SimplifierUrlKey
  ${{ if ne(parameters.Environment, 'Prod') }}:
    value: $SIMPLIFIER_DEV_URLKEY
  ${{ else }}:
    value: $SIMPLIFIER_PROD_URLKEY


stages:
  - stage: Deploy
    jobs:
      - deployment: DeployJob
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: UseDotNet@2
                  inputs:
                    version: '8.x'

                - script: |
                    echo "Install Firely.Terminal"
                    if ! command -v fhir ; then
                      dotnet tool install --global Firely.Terminal 
                    fi
                  displayName: 'Install Firely.Terminal'

                - script: |
                    echo "Check Firely Terminal Version"
                    CHECK_FIRELY_TERMINAL_VERSION=$(fhir -v | tr '\n' ' ')
                    echo "FIRELY_TERMINAL_VERSION: $CHECK_FIRELY_TERMINAL_VERSION"
                  displayName: 'Check Firely Terminal Version'

                - script: |
                    echo "Simplifier login and sync"
                    fhir login email=$SIMPLIFIER_USERNAME password=$SIMPLIFIER_PASSWORD
                    tree
                    fhir project link ${{variables.SimplifierUrlKey}} --strategy TakeLocal
                    tree
                    fhir project sync
                    tree
                  displayName: 'Simplifier login and sync'
                  env:
                    SIMPLIFIER_USERNAME: $(SIMPLIFIER_USERNAME)
                    SIMPLIFIER_PASSWORD: $(SIMPLIFIER_PASSWORD)