# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  - feature/*

pool:
  vmImage: ubuntu-latest

parameters:
  - name: Environment
    displayName: Specify the simplifier environment
    default: DEV
    type: string

variables:
- group: Simplifier
- name: SimplifierUrlKey
  ${{ if eq(parameters.Environment, 'PROD') }}:
    value: $SIMPLIFIER_PROD_URLKEY
  ${{ else }}:
    value: $SIMPLIFIER_TEST_URLKEY

steps:
- task: UseDotNet@2
  inputs:
    version: '8.x'

- script: |
    echo "Install Firely.Terminal"
    if ! command -v fhir; then
      dotnet tool install --global Firely.Terminal 
    fi
  displayName: 'Install Firely.Terminal'

- script: |
    echo "Check Firely Terminal Version"
    CHECK_FIRELY_TERMINAL_VERSION=$(fhir -v | tr '\n' ' ')
    echo "FIRELY_TERMINAL_VERSION: $CHECK_FIRELY_TERMINAL_VERSION"
  displayName: 'Check Firely Terminal Version'

- script: |
    echo "Simplifier login and sync"
    fhir login email=$SIMPLIFIER_USERNAME password=$SIMPLIFIER_PASSWORD
    fhir project link ${{variables.SimplifierUrlKey}} --strategy TakeLocal
    fhir project sync
  displayName: 'Simplifier login and sync'
  env:
    SIMPLIFIER_USERNAME: $(SIMPLIFIER_USERNAME)
    SIMPLIFIER_PASSWORD: $(SIMPLIFIER_PASSWORD)
