# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main

pool:
  vmImage: ubuntu-latest

parameters:
  - name: Environment
    displayName: 'Choose an option'
    type: string
    default: 'Dev'
    values:
      - Dev
      - Test
      - Prod

variables:
- group: Simplifier
- name: SimplifierUrlKey
  ${{ if ne(parameters.Environment, 'PROD') }}:
    value: $SIMPLIFIER_DEV_URLKEY
  ${{ else }}:
    value: $SIMPLIFIER_PROD_URLKEY


stages:
  - stage: Deploy
    jobs:
      - deployment: DeployJob
        environment: ${{ parameters.environment }}
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo "Deploying to ${{ parameters.environment }} environment"
                  displayName: 'Deploy'