## Pipeline to enable a deployment to the Development project within Simplifier
trigger:
  - main

pool:
  vmImage: 'ubuntu-22.04'

variables:
- group: Simplifier

steps:
  - task: UseDotNet@2
    inputs:
      version: '8.x'

  - script: |
      echo "Install Firely.Terminal"
      if ! command -v fhir ; then
        dotnet tool install --global Firely.Terminal 
      fi
    displayName: 'Install Firely.Terminal'

  - script: |
      echo "Check Firely Terminal Version"
      CHECK_FIRELY_TERMINAL_VERSION=$(fhir -v | tr '\n' ' ')
      echo "FIRELY_TERMINAL_VERSION: $CHECK_FIRELY_TERMINAL_VERSION"
    displayName: 'Check Firely Terminal Version'

  - script: |
      echo "Simplifier login and sync"
      fhir login email=$SIMPLIFIER_USERNAME password=$SIMPLIFIER_PASSWORD
      fhir project link $SIMPLIFIER_DEV_URLKEY --strategy TakeLocal
      fhir project sync
    displayName: 'Simplifier login and sync'
    env:
      SIMPLIFIER_USERNAME: $(SIMPLIFIER_USERNAME)
      SIMPLIFIER_PASSWORD: $(SIMPLIFIER_PASSWORD)